---
server_name: finjal.dev
symfony_root_dir: /var/www/finjal
symfony_web_dir: "{{ symfony_root_dir }}/web"
symfony_var_dir: "{{ symfony_root_dir }}/var"
symfony_console_path: "{{ symfony_root_dir }}/bin/console"
symfony_secret: "{{ vault_symfony_secret }}"